peak/s5cmd

README.md
Vendored package `github.com/posener/complete` uses `os.Executable`, and it's added in Go 1.8.
```
~$ go version
go version go1.7 linux/amd64
~$ go get -u github.com/peakgames/s5cmd
$GOPATH/src/github.com/peakgames/s5cmd/vendor/github.com/posener/complete/cmd/install/install.go:75: undefined: os.Executable
```
=> readme: update minimum go version

README.md, complete/complete.go, core/s3.go, core/worker.go, s5cmd.go
Adds cli flag to override default endpoint, so it can be used with other S3 compatible services.
resolve #4
=> Endpoint support for S3 compatible services

core/job.go
Not all S3 compatible services support StorageClass functionality. I.e. Google Cloud Storage, in-memory S3 services.
=> core: check if StorageClass is nil

s3url/s3url.go, s3url/s3url_test.go
URL parse for non-batch operations is not working as expected if the prefix is not a directory. This behaviour was broken on 3e51198607e7a45566f7df1cee1cc2a2ebfe9384.
For the prefix `tmp`, following key will result with `_key`
```
request: s5cmd ls s3://bucket/tmp
response: tmp_key
prefix: tmp
current output: _key 
expected output: tmp_key
```
This PR fixes this issue.
=> Correctly parse key if prefix is not a directory

core/job.go, core/jobargument.go, core/scan.go, core/worker.go
Currently, workers are running without validating jobs. 
Help command should be isolated from the worker pool. Also, if the jobs are not valid, we should not start workers. This PR makes the following improvements:
- Remove `HELP` command from AcceptableErrors.
- Don't send help commands to the job queue.
- Start workers if jobs are parsable and not help.
- Use deferred calls for closing channels.
=> Start workers after validating jobs

core/job_batch.go, e2e/cp_test.go
=> core: fix relative copy regression

core/command.go, core/commands.go, core/job_exec.go, core/parse.go, e2e/mb_test.go, objurl/objurl.go, objurl/objurl_test.go, op/op.go, opt/opt.go, storage/fs.go, storage/s3.go, storage/storage.go
- added mb (make bucket) command
=> Add mb (make-bucket) command

storage/s3.go, storage/s3_test.go
Amazon S3, S3 Transfer Acceleration and Google Cloud Storage known to support virtual-style bucket resolve method. For other types of endpoints, such as custom object store or localhost, use path-style bucket name resolve method.
Related: #92
=> Use virtual-style if the endpoint is known to has support

command/cmd_copy.go, command/cmd_list.go, command/cmd_size.go, storage/fs.go, storage/s3.go, storage/s3_test.go, storage/storage.go
We are using a full scan mode on storage.List() operations and do not need maxKeys param for this release. It was used by s3 predictor. Once we decided to reimplement it, we can add this parameter again.
=> storage: Remove maxKeys parameter from List

storage/s3.go, storage/s3_test.go
We occasionally receive InternalError codes from S3 API. It was on our retry list before.
Adding a custom retryer that implements request.Retryer interface.
=> storage/s3: add custom retryer for custom error codes

e2e/rm_test.go
Let's see if it's still flaky after CircleCI change
=> e2e: enable RemoveTenThousandS3Objects test

command/cp.go
Using nested multierrors is not fun.
=> command/copy: ignore delete errors if download is canceled

command/cp.go
* Adds examples for s3 to s3 copy operation
* Also, fixes typo for mirroring an S3 prefix example
=> cp: Add remote copy examples to help text

command/cp.go, command/ls.go, command/mv.go, e2e/cp_test.go, e2e/util_test.go, storage/s3.go, storage/storage.go
- e2e/cp: add --storage-class=GLACIER test
- also show 2 character storage class short code in 'ls' output
If you pass an invalid storage class, S3 will return:
```
s5cmd cp --storage-class=invalidstorageclass file s3://bucket/
ERROR "cp file s3://bucket/file": InvalidStorageClass: The storage class you specified is not valid status code: 400...
```
Fixes #160
=> storage/s3: allow any storage-class value

command/cp.go, e2e/cp_test.go, storage/s3.go
If we don't provide `--storage-class` flag, cp gives InvalidStorageClass error on the master branch. I think it should be useful to give a default value for this flag. Also, updated usage to include new storage class types.
=> cp: Set storage class if provided

command/app.go
Replace obsolete global option value in app.go
The value `verbose` for global option `--log` has been deprecated in favor of `debug`. This fixes #173 .
=> Replace obsolete global option value in app.go

.github/workflows/ci.yml, Makefile
- Add Windows build support
- Add macOS build support
- Use a build matrix to run jobs for multiple operating systems and Go versions
Fixes #95
=> ci: add Github Actions support

storage/s3.go, storage/s3_test.go
We upload large amount of data to s3 and after upgrading version 1.0.0 ,  we experienced failures for large uploads , randomly we get errors like below.
`RequestError: send request failed
caused by: Put "https://testing.s3.amazonaws.com/xxxxx&partNumber=n&uploadId=id": write tcp 10.xx.xx.xx:41654->52.216.8.115:443: use of closed network connection`
After digging AWS SDK `ShouldRetry` method, we noticed that for some cases it does return `false` but for some cases it returns `true` even if base error says `use of closed network connection` in both cases, you can see below
`SerializationError: failed to unmarshal error message
status code: 500, request id: IDDDDDDD, host id: 3231sdsadasdasdI=
caused by: UnmarshalError: failed to unmarshal error message
caused by: read tcp …
=> Retry on closed connection

.goreleaser.yml
Test cases with wildcards and List calls are flaky due to gofakes3 with the changes in #188. Disabling before hooks until it is fixed.
=> goreleaser: disable before hooks

Dockerfile, Makefile, README.md
=> dockerfile: add dockerfile
